-- migrate:up
CREATE TABLE users(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE KEY,
    password VARCHAR(200) NOT NULL,
    name VARCHAR(200) NOT NULL,
    birth VARCHAR(100) NOT NULL,
    phone_number VARCHAR(100) NOT NULL UNIQUE KEY,
    address VARCHAR(500) NULL,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP
);

-- migrate:down
DROP TABLE users;
